name: 'Amazon ECS "Render Task Definition" Action'
description: 'Modify your container definition in an Amazon ECS task definition JSON file, creating a new file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  image:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
  aws-sm-name:
    description: 'The name of secrets manager to be retrieved'
    required: false
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'
